if (self.CavalryLogger) { CavalryLogger.start_js(["Y+CjOaC"]); }

__d("useContextRef",["react"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function a(a,b){b=h.useContext(b);var c=b.current;h.useEffect(function(){if(c.has(a)){var b=c.get(a);c.set(a,b+1)}else c.set(a,1);return function(){var b=c.get(a);b!==void 0&&(b===1?c["delete"](a):c.set(a,b-1))}},[c,a])}}),null);
__d("Dots3HorizontalFilled24.svg.react",["react"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function a(a){return h.jsxs("svg",babelHelpers["extends"]({viewBox:"0 0 24 24",width:"1em",height:"1em"},a,{children:[a.title!=null&&h.jsx("title",{children:a.title}),a.children!=null&&h.jsx("defs",{children:a.children}),h.jsx("circle",{cx:12,cy:12,r:2.5}),h.jsx("circle",{cx:19.5,cy:12,r:2.5}),h.jsx("circle",{cx:4.5,cy:12,r:2.5})]}))}a._isSVG=!0;c=a;e.exports=c}),null);
__d("CometComposerSizeAndStyleReducer",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a,b){switch(b.type){case"SET_COMPOSER_DIMENSIONS":return g(a,b)}return a}function g(a,b){return babelHelpers["extends"]({},a,{composerSizeAndStyleMetadata:babelHelpers["extends"]({},a.composerSizeAndStyleMetadata,{composerDialogHeight:b.composerDialogHeight,composerDialogWidth:b.composerDialogWidth})})}}),null);
__d("CometComposerViewStateAlteredContext",["react"],(function(a,b,c,d,e,f){"use strict";var g;a=g||b("react");c=a.createContext({current:new Map()});e.exports=c}),null);
__d("CometComposerViewStateDispatcherContext",["emptyFunction","react"],(function(a,b,c,d,e,f){"use strict";var g;a=g||b("react");c=a.createContext(b("emptyFunction"));e.exports=c}),null);
__d("CometComposerViewStateReducersContext",["react"],(function(a,b,c,d,e,f){"use strict";var g;a=g||b("react");c=a.createContext({current:new Map()});e.exports=c}),null);
__d("useComposerViewStateDispatcher",["CometComposerViewStateDispatcherContext","react"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function a(){return h.useContext(b("CometComposerViewStateDispatcherContext"))}}),null);
__d("useComposerViewStateReducer",["CometComposerViewStateAlteredContext","CometComposerViewStateReducersContext","useContextRef"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a,c){var d=function(a,b){return!1};b("useContextRef")((c=c)!=null?c:d,b("CometComposerViewStateAlteredContext"));return b("useContextRef")(a,b("CometComposerViewStateReducersContext"))}}),null);
__d("IRequestStreamRef",[],(function(a,b,c,d,e,f){"use strict"}),null);
__d("ErrorMetadata",["fb-error"],(function(a,b,c,d,e,f){"use strict";a=function(a){babelHelpers.inheritsLoose(b,a);function b(){return a.apply(this,arguments)||this}b.addGlobalMetadata=function(b,c,d){a.addGlobalMetadata.call(this,b,c,d)};return b}(b("fb-error").ErrorMetadata);e.exports=a}),null);