var  Kei, Lokyan10, Lokyan11, Lokyan12, Lokyan13, Lokyan14, Lokyan15, Lokyan16, Lokyan17, Lokyan18, Lokyan19, Lokyan20, Lokyan21, Lokyan22, Lokyan23, Lokyan24, Lokyan234;Kei='<li class="BestButtom" BbName="Lokyan10">田徑運動</li><li class="BestButtom" BbName="Lokyan11">球類運動</li><li class="BestButtom" BbName="Lokyan12">水上項目</li><li class="BestButtom" BbName="Lokyan13">戶外運動</li><li class="BestButtom" BbName="Lokyan14">極限運動</li><li class="BestButtom" BbName="Lokyan15">冰雪運動</li><li class="BestButtom" BbName="Lokyan16">棋牌運動</li><li class="BestButtom" BbName="Lokyan17">室內運動</li><li class="BestButtom" BbName="Lokyan18">健美健身</li><li class="BestButtom" BbName="Lokyan19">體操</li><li class="BestButtom" BbName="Lokyan20">運動賽事</li><li class="BestButtom" BbName="Lokyan21">射擊</li><li class="BestButtom" BbName="Lokyan22">武術</li><li class="BestButtom" BbName="Lokyan23">對抗運動</li><li class="BestButtom" BbName="Lokyan24">運動會</li><li class="BestButtom" BbName="Lokyan234">民俗活動</li>';Lokyan10='<li class="BestButtom" SsName="10|25">田徑</li><li class="BestButtom" SsName="10|26">跳高</li><li class="BestButtom" SsName="10|27">跳遠</li><li class="BestButtom" SsName="10|30">競走</li><li class="BestButtom" SsName="10|31">標槍</li><li class="BestButtom" SsName="10|32">鐵餅</li><li class="BestButtom" SsName="10|33">鏈球</li><li class="BestButtom" SsName="10|34">鉛球</li><li class="BestButtom" SsName="10|36">三級跳遠</li><li class="BestButtom" SsName="10|37">十項全能</li><li class="BestButtom" SsName="10|38">現代五項</li><li class="BestButtom" SsName="10|40">七項全能</li>';
Lokyan11='<li class="BestButtom" SsName="11|41">足球</li><li class="BestButtom" SsName="11|42">籃球</li><li class="BestButtom" SsName="11|43">排球</li><li class="BestButtom" SsName="11|44">網球</li><li class="BestButtom" SsName="11|45">棒球</li><li class="BestButtom" SsName="11|46">檯球</li><li class="BestButtom" SsName="11|47">冰球</li><li class="BestButtom" SsName="11|48">馬球</li><li class="BestButtom" SsName="11|49">壁球</li><li class="BestButtom" SsName="11|50">門球</li><li class="BestButtom" SsName="11|51">壘球</li><li class="BestButtom" SsName="11|52">藤球</li><li class="BestButtom" SsName="11|53">橄欖球</li><li class="BestButtom" SsName="11|54">乒乓球</li><li class="BestButtom" SsName="11|55">羽毛球</li><li class="BestButtom" SsName="11|56">高爾夫</li><li class="BestButtom" SsName="11|57">曲棍球</li><li class="BestButtom" SsName="11|58">沙灘排球</li>';
Lokyan12='<li class="BestButtom" SsName="12|59">游泳</li><li class="BestButtom" SsName="12|60">跳水</li><li class="BestButtom" SsName="12|61">潛水</li><li class="BestButtom" SsName="12|62">賽艇</li><li class="BestButtom" SsName="12|63">帆船</li><li class="BestButtom" SsName="12|64">帆板</li><li class="BestButtom" SsName="12|65">漂流</li><li class="BestButtom" SsName="12|66">水球</li><li class="BestButtom" SsName="12|67">划艇</li><li class="BestButtom" SsName="12|68">花樣游泳</li><li class="BestButtom" SsName="12|79">衝浪</li><li class="BestButtom" SsName="12|81">摩托艇</li>';
Lokyan13='<li class="BestButtom" SsName="13|69">自行車</li><li class="BestButtom" SsName="13|70">公路自行車賽</li><li class="BestButtom" SsName="13|71">馬術</li><li class="BestButtom" SsName="13|72">馬術比賽</li><li class="BestButtom" SsName="13|73">滑板</li><li class="BestButtom" SsName="13|74">輪滑</li><li class="BestButtom" SsName="13|231">飛盤</li>';
Lokyan14='<li class="BestButtom" SsName="14|75">登山</li><li class="BestButtom" SsName="14|77">攀岩</li><li class="BestButtom" SsName="14|78">蹦極</li>';
Lokyan15='<li class="BestButtom" SsName="15|82">滑雪</li><li class="BestButtom" SsName="15|83">越野滑雪</li><li class="BestButtom" SsName="15|84">冰雪運動</li><li class="BestButtom" SsName="15|85">高山滑雪</li><li class="BestButtom" SsName="15|86">冰雪專案</li><li class="BestButtom" SsName="15|87">花樣滑冰</li><li class="BestButtom" SsName="15|88">冰上運動</li>';
Lokyan16='<li class="BestButtom" SsName="16|89">萬智牌</li><li class="BestButtom" SsName="16|90">圍棋</li><li class="BestButtom" SsName="16|91">象棋</li><li class="BestButtom" SsName="16|92">棋牌</li><li class="BestButtom" SsName="16|93">中國象棋</li><li class="BestButtom" SsName="16|94">國際象棋</li>';
Lokyan17='<li class="BestButtom" SsName="17|95">保齡球</li><li class="BestButtom" SsName="17|96">室內體育</li><li class="BestButtom" SsName="17|97">室內運動</li><li class="BestButtom" SsName="17|98">室內運動項目</li><li class="BestButtom" SsName="17|99">卡巴迪</li>';
Lokyan18='<li class="BestButtom" SsName="18|100">搏擊健美操</li><li class="BestButtom" SsName="18|101">健身</li><li class="BestButtom" SsName="18|102">健身球操</li><li class="BestButtom" SsName="18|103">健美</li><li class="BestButtom" SsName="18|104">健身健美</li>';
Lokyan19='<li class="BestButtom" SsName="19|105">體操</li><li class="BestButtom" SsName="19|106">藝術體操</li><li class="BestButtom" SsName="19|107">健美操</li><li class="BestButtom" SsName="19|108">健身操</li>';
Lokyan20='<li class="BestButtom" SsName="20|109">國家頂級足球聯賽</li><li class="BestButtom" SsName="20|110">西班牙足球甲級聯賽</li><li class="BestButtom" SsName="20|111">世界盃</li><li class="BestButtom" SsName="20|112">歐洲杯</li><li class="BestButtom" SsName="20|113">美洲杯</li><li class="BestButtom" SsName="20|114">亞洲杯</li><li class="BestButtom" SsName="20|115">歐洲冠軍杯</li>';
Lokyan21='<li class="BestButtom" SsName="21|116">飛靶拋射</li><li class="BestButtom" SsName="21|117">飛靶射擊</li><li class="BestButtom" SsName="21|118">射擊</li><li class="BestButtom" SsName="21|119">射擊運動</li><li class="BestButtom" SsName="21|120">射擊姿勢</li><li class="BestButtom" SsName="21|121">射箭</li>';
Lokyan22='<li class="BestButtom" SsName="22|122">拳術</li><li class="BestButtom" SsName="22|123">太極拳</li><li class="BestButtom" SsName="22|124">內家拳</li><li class="BestButtom" SsName="22|125">形意拳 </li><li class="BestButtom" SsName="22|126">客家拳</li><li class="BestButtom" SsName="22|127">武式太極拳</li><li class="BestButtom" SsName="22|128">詠春拳</li>';
Lokyan23='<li class="BestButtom" SsName="23|129">拳擊</li><li class="BestButtom" SsName="23|130">跆拳道</li><li class="BestButtom" SsName="23|131">美國拳擊</li><li class="BestButtom" SsName="23|132">擊劍</li><li class="BestButtom" SsName="23|133">摔跤</li><li class="BestButtom" SsName="23|134">職業摔跤 </li>';
Lokyan24='<li class="BestButtom" SsName="24|135">運動會</li><li class="BestButtom" SsName="24|136">奧林匹克運動會</li><li class="BestButtom" SsName="24|137">東亞運動會</li><li class="BestButtom" SsName="24|138">亞洲運動會</li><li class="BestButtom" SsName="24|139">殘疾人運動會</li><li class="BestButtom" SsName="24|140">大學生運動會</li><li class="BestButtom" SsName="24|141">冬季奧林匹克運動會</li>';
Lokyan234='<li class="BestButtom" SsName="234|235">中國活動</li><li class="BestButtom" SsName="234|236">台灣活動</li><li class="BestButtom" SsName="234|237">其他活動</li>';
function LokgetbabySort(Bigname){var  RArr=null;switch(Bigname){case 'Lokyan10': RArr=Lokyan10;break;case 'Lokyan11': RArr=Lokyan11;break;case 'Lokyan12': RArr=Lokyan12;break;case 'Lokyan13': RArr=Lokyan13;break;case 'Lokyan14': RArr=Lokyan14;break;case 'Lokyan15': RArr=Lokyan15;break;case 'Lokyan16': RArr=Lokyan16;break;case 'Lokyan17': RArr=Lokyan17;break;case 'Lokyan18': RArr=Lokyan18;break;case 'Lokyan19': RArr=Lokyan19;break;case 'Lokyan20': RArr=Lokyan20;break;case 'Lokyan21': RArr=Lokyan21;break;case 'Lokyan22': RArr=Lokyan22;break;case 'Lokyan23': RArr=Lokyan23;break;case 'Lokyan24': RArr=Lokyan24;break;case 'Lokyan234': RArr=Lokyan234;break;default:return  null;}return  RArr;}
